---
stages:
  - build
  - test
  - sonar

# JOB_INT: [ 32 | 64 | 32-64 ]
# JOB_THREAD: [ n | c | k | s | m ]
# JOB_DETERMINISTIC: [ n | d ]
# JOB_DEBUG: [ n | a | f ]
# JOB_RENAME: [ n | r ]
.matrix_32: &matrix_32
  parallel:
    matrix:
      - JOB_INT: [32, 32-64]
        JOB_THREAD: [n]
        JOB_DETERMINISTIC: [n]
        JOB_DEBUG: [n]
        JOB_RENAME: [n]
      - JOB_INT: [32-64]
        JOB_THREAD: [n, k]
        JOB_DETERMINISTIC: [d]
        JOB_DEBUG: [a]
        JOB_RENAME: [n]
      - JOB_INT: [32]
        JOB_THREAD: [n, c, m]
        JOB_DETERMINISTIC: [n]
        JOB_DEBUG: [f]
        JOB_RENAME: [n]

.matrix_64: &matrix_64
  parallel:
    matrix:
      - JOB_INT: [64]
        JOB_THREAD: [n]
        JOB_DETERMINISTIC: [n]
        JOB_DEBUG: [n]
        JOB_RENAME: [n]
      - JOB_INT: [64]
        JOB_THREAD: [n, c, s, m]
        JOB_DETERMINISTIC: [d]
        JOB_DEBUG: [a]
        JOB_RENAME: [n]
      - JOB_INT: [64]
        JOB_THREAD: [m]
        JOB_DETERMINISTIC: [n]
        JOB_DEBUG: [a]
        JOB_RENAME: [r]


# GNU Makefile pipeline

## Build

.build_makefile: &build_makefile
  stage: build
  script:
    - ./ci/build_makefile.sh
  interruptible: true

scotch_build_32:
  <<: *build_makefile
  tags: ['32bits']
  <<: *matrix_32
  artifacts:
    untracked: true
    exclude:
      - "**/*.o"
    expire_in: 1 week

scotch_build_64:
  <<: *build_makefile
  tags: ['64bits']
  <<: *matrix_64
  artifacts:
    untracked: true
    exclude:
      - "**/*.o"
    expire_in: 1 week

## Test

.test_makefile: &test_makefile
  stage: test
  artifacts:
    untracked: true
    expire_in: 15 days
  script:
    - ./ci/test_makefile.sh
  interruptible: true

scotch_test_32:
  <<: *test_makefile
  tags: ['32bits']
  <<: *matrix_32
  needs:
    - job: scotch_build_32
      parallel:
        matrix:
          - JOB_INT: ['$[[ matrix.JOB_INT ]]']
            JOB_THREAD: ['$[[ matrix.JOB_THREAD ]]']
            JOB_DETERMINISTIC: ['$[[ matrix.JOB_DETERMINISTIC ]]']
            JOB_DEBUG: ['$[[ matrix.JOB_DEBUG ]]']
            JOB_RENAME: ['$[[ matrix.JOB_RENAME ]]']

scotch_test_64:
  <<: *test_makefile
  tags: ['64bits']
  <<: *matrix_64
  needs:
    - job: scotch_build_64
      parallel:
        matrix:
          - JOB_INT: ['$[[ matrix.JOB_INT ]]']
            JOB_THREAD: ['$[[ matrix.JOB_THREAD ]]']
            JOB_DETERMINISTIC: ['$[[ matrix.JOB_DETERMINISTIC ]]']
            JOB_DEBUG: ['$[[ matrix.JOB_DEBUG ]]']
            JOB_RENAME: ['$[[ matrix.JOB_RENAME ]]']

## Sonarqube analysis if scheduled job

scotch_sonar:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: sonar
  tags: ['sonar']
  script:
    - ci/analysis.sh
    - sonar-scanner -X > sonar.log
  allow_failure: true
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    paths:
      - analyzer_reports
      - sonar-project.properties
      - ./*.log
      - ./*.cov
      - ./*.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 15 days

# CMake pipeline (not done if scheduled)

## Specific rule: not triggered if scheduled pipeline (for CMake jobs, for example)

.rule_noschedule: &rule_noschedule
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

## Build
## Use a custom build directory setting GIT_CLONE_PATH
## because CMake uses absolute paths and needs a stable directory between builds and tests

.build_cmake: &build_cmake
  <<: *rule_noschedule
  stage: build
  tags: ['cmake']
  script:
    - ./ci/build_cmake.sh
  interruptible: true
  artifacts:
    paths:
      - build/
    exclude:
      - "**/*.o"
    expire_in: 1 week

build_cmake_gcc:
  <<: *build_cmake
  variables:
    CC: "gcc"
    FC: "gfortran"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_gcc

build_cmake_clang:
  <<: *build_cmake
  variables:
    CC: "clang"
    FC: "gfortran"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_clang

build_cmake_intel:
  <<: *build_cmake
  tags: ['64bits']
  variables:
    CC: "icx"
    FC: "gfortran"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_intel

build_cmake_pgi:
  <<: *build_cmake
  tags: ['64bits']
  variables:
    CC: "pgcc"
    FC: "pgf90"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_pgi

## Test
## Use the same GIT_CLONE_PATH as the build

.test_cmake: &test_cmake
  <<: *rule_noschedule
  stage: test
  tags: ['cmake']
  script:
    - ./ci/test_cmake.sh
  artifacts:
    untracked: true
    reports:
      junit: report.xml
    expire_in: 15 days
  interruptible: true

test_cmake_gcc:
  <<: *test_cmake
  needs:
    - build_cmake_gcc
  variables:
    CC: "gcc"
    FC: "gfortran"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_gcc

test_cmake_clang:
  <<: *test_cmake
  needs:
    - build_cmake_clang
  variables:
    CC: "clang"
    FC: "gfortran"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_clang

test_cmake_intel:
  <<: *test_cmake
  needs:
    - build_cmake_intel
  variables:
    CC: "icx"
    FC: "ifx"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_intel

test_cmake_pgi:
  <<: *test_cmake
  needs:
    - build_cmake_pgi
  variables:
    CC: "pgcc"
    FC: "pgf90"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/cmake_pgi
